version: 2
updates:
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "weekly"
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
    - package-ecosystem: "npm"
      directory: "/frontend"
      schedule:
          interval: "weekly"
    - package-ecosystem: "npm"
      directory: "/bot"
      schedule:
          interval: "weekly"
