# markdownlint-cli2 configuration
# Uses existing .markdownlint.json for rules and .markdownlintignore for excludes
# Note: globs removed to allow pre-commit to control which files are checked

config:
    extends: ".markdownlint.json"

# globs removed - pre-commit will pass only staged markdown files

ignores:
    - "**/node_modules/**"
    - "node_modules/**"
    - "**/node_modules/**"
    - "aar/node_modules/**"
    - "frontend/node_modules/**"
    - "bot/node_modules/**"
    - "app/aar-ui/node_modules/**"
    - "app/aar-core/node_modules/**"
    - "htmlcov/**"
    - ".venv/**"
    - "venv/**"
    - "*.egg-info/**"
    - "archive/**"
    - "logs/**"
    - "tmp/**"
    - ".git/**"
    - "Potato.md" # Potato Policy - contains sensitive SSH/setup info
    - ".github/ISSUE_TEMPLATE/bug_report.md" # Temporary - testing AAR compliance
