name: Setup GitHub CLI
runs:
  using: composite
  steps:
    - name: Install GitHub CLI
      uses: actions/setup-gh@v4
    - name: Log gh version
      shell: bash
      run: |
        which gh
        gh --version
