name: Setup GitHub CLI
runs:
  using: composite
  steps:
    - name: Install GitHub CLI
      shell: bash
      run: |
        set -e
        if [ "$RUNNER_OS" = "Windows" ]; then
            choco install gh --no-progress --yes
        elif [ "$RUNNER_OS" = "macOS" ]; then
            brew install gh
        else
            sudo rm -f /usr/bin/gh || true
            sudo mkdir -p -m 0755 /etc/apt/keyrings
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg |
              sudo dd of=/etc/apt/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" |
              sudo tee /etc/apt/sources.list.d/github-cli.list >/dev/null
            sudo apt-get update
            sudo apt-get install -y gh
        fi
        echo "/usr/local/bin" >> "$GITHUB_PATH"
        which gh
        gh --version
