name: Security Scanning Template

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1'  # Weekly security scan

jobs:
  security-scan:
    permissions:
      contents: read           # Required for checkout
      security-events: write   # Required for uploading SARIF results
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create virtual environment
        run: python -m venv .venv

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          pip install -e .[test]

      - name: Run Bandit security scan
        run: |
          source .venv/bin/activate
          python -m bandit -r src/ -f json -o bandit-results.json || true

      - name: Run safety check for dependencies
        run: |
          source .venv/bin/activate
          python -m safety check --json --output safety-results.json || true

      - name: Upload security scan results
        if: always()
        run: |
          # Upload results to security tab if SARIF format available
          echo "Security scan completed"
