# TOKEN: CI_ISSUE_AUTOMATION_TOKEN (issue creation and management)
# PERMISSIONS: contents:read, issues:write, pull-requests:write
# PURPOSE: Generate automated After Action Reports for CI failures
# COMPLIANCE: Universal Workflow Permissions Policy + No Default Token Policy v1.0
# SCOPE: Triggered by CI, PR Automation, and Auto-Fix workflow completions

name: "After Action Report (AAR) Generator"

# DevOnboarder AAR System - Automated CI failure analysis with token governance

on:
  workflow_run:
    workflows:
      - "CI"
      - "PR Automation"
      - "Auto-Fix"
      - "Documentation Quality"
      - "Security Audit"
    types: [completed]
    branches:
      - main
      - "feature/**"

  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: "Specific workflow run ID to analyze"
        required: false
        type: string
      create_issue:
        description: "Create GitHub issue for AAR report"
        required: false
        type: boolean
        default: true

permissions:
  contents: read

env:
  # CRITICAL: Follow DevOnboarder No Default Token Policy v1.0
  # Token hierarchy: CI_ISSUE_AUTOMATION_TOKEN -> CI_BOT_TOKEN -> built-in GITHUB_TOKEN
  PYTHON_ENV: ci
  NODE_ENV: test
  CI: true

jobs:
  generate-aar:
    name: "Generate After Action Report"
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'failure' || github.event_name == 'workflow_dispatch' }}

    permissions:
      # Minimal permissions for AAR generation
      contents: read
      issues: write
      actions: read
      # uncomment if your script reads checks or PRs:
      # checks: read
      # pull-requests: read

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 50  # Get recent history for change analysis

      - name: "Setup Python environment"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: "Create virtual environment"
        run: |
          python -m venv .venv
          source .venv/bin/activate
          printf "VIRTUAL_ENV=%s\n" "$VIRTUAL_ENV" >> $GITHUB_ENV
          printf "%s/bin\n" "$VIRTUAL_ENV" >> $GITHUB_PATH

      - name: "Install dependencies"
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -e .[test]

      # --- Token selection (policy: CI_ISSUE_AUTOMATION_TOKEN -> CI_BOT_TOKEN -> built-in) ---
      - name: "Select automation token"
        id: pick-token
        shell: bash
        env:
          S1: ${{ secrets.CI_ISSUE_AUTOMATION_TOKEN }}
          S2: ${{ secrets.CI_BOT_TOKEN }}
          BUILTIN: ${{ github.token }}  # absolute fallback only
        run: |
          if [ -n "$S1" ]; then TOKEN="$S1";
          elif [ -n "$S2" ]; then TOKEN="$S2";
          else TOKEN="$BUILTIN"; fi
          printf 'token=%s\n' "$TOKEN" >> "$GITHUB_OUTPUT"
          if [ "$TOKEN" = "$BUILTIN" ]; then
            echo "::notice title=Token Selection::Using BUILT-IN token (fallback)"
          else
            echo "::notice title=Token Selection::Using FINE-GRAINED secret"
          fi

      # Optional hard-fail if only built-in token is available (strict mode)
      # - name: "Enforce No-Default-Token policy (block if fallback)"
      #   if: ${{ steps.pick-token.outputs.token == github.token }}
      #   run: |
      #     echo "Policy violation: refusing to use built-in token in this job." >&2
      #     exit 1

      - name: "Validate AAR environment"
        env:
          # Pass the selected token for scripts that may call GitHub API
          GITHUB_TOKEN: ${{ steps.pick-token.outputs.token }}
        run: |
          source .venv/bin/activate
          python scripts/aar_security.py

      - name: "Create file version snapshot"
        run: |
          source .venv/bin/activate
          python scripts/file_version_tracker.py --create-snapshot "pre-aar-${GITHUB_RUN_ID}"

      - name: "Generate AAR report"
        env:
          # CRITICAL: Use proper token hierarchy for AAR operations
          CI_ISSUE_AUTOMATION_TOKEN: ${{ secrets.CI_ISSUE_AUTOMATION_TOKEN }}
          CI_BOT_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          # Unified token selection result (do not rename)
          GITHUB_TOKEN: ${{ steps.pick-token.outputs.token }}

          # Workflow context for analysis
          WORKFLOW_RUN_ID: ${{ github.event.workflow_run.id || github.event.inputs.workflow_run_id }}
          TRIGGER_WORKFLOW: ${{ github.event.workflow_run.name || 'manual' }}
          FAILURE_CONCLUSION: ${{ github.event.workflow_run.conclusion || 'unknown' }}
        run: |
          source .venv/bin/activate
          printf 'Starting AAR generation for workflow run: %s\n' "$WORKFLOW_RUN_ID"
          printf 'Triggered by: %s\n' "$TRIGGER_WORKFLOW"
          printf 'Conclusion: %s\n' "$FAILURE_CONCLUSION"

          if [ -n "$WORKFLOW_RUN_ID" ]; then
            python scripts/generate_aar.py \
              --workflow-run-id "$WORKFLOW_RUN_ID" \
              --config "config/aar-config.json" \
              --output-file "aar_${WORKFLOW_RUN_ID}_${GITHUB_RUN_ID}.md"
          else
            python scripts/generate_aar.py \
              --config "config/aar-config.json" \
              --output-file "aar_general_${GITHUB_RUN_ID}.md"
          fi

      - name: "Create GitHub issue"
        # If manually dispatched, respect the boolean input; for workflow_run, always create
        if: ${{ (github.event_name == 'workflow_dispatch' && inputs.create_issue) || (github.event_name != 'workflow_dispatch') }}
        env:
          CI_ISSUE_AUTOMATION_TOKEN: ${{ secrets.CI_ISSUE_AUTOMATION_TOKEN }}
          CI_BOT_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          GITHUB_TOKEN: ${{ steps.pick-token.outputs.token }}
          WORKFLOW_RUN_ID: ${{ github.event.workflow_run.id || github.event.inputs.workflow_run_id }}
        run: |
          source .venv/bin/activate

          if [ -n "$WORKFLOW_RUN_ID" ]; then
            python scripts/generate_aar.py \
              --workflow-run-id "$WORKFLOW_RUN_ID" \
              --create-issue \
              --config "config/aar-config.json"
          else
            python scripts/generate_aar.py \
              --create-issue \
              --config "config/aar-config.json"
          fi

      - name: "Archive AAR artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "aar-reports-${{ github.run_id }}"
          path: |
            logs/aar/*.md
            logs/aar-reports/*.md
            logs/token-audit/*.json
            logs/file-versions.json
          retention-days: 30

      - name: "Generate change analysis"
        env:
          GITHUB_TOKEN: ${{ steps.pick-token.outputs.token }}
        run: |
          source .venv/bin/activate

          # Create post-AAR snapshot for comparison
          python scripts/file_version_tracker.py --create-snapshot "post-aar-${GITHUB_RUN_ID}"

          # Analyze Git changes if we have workflow context
          if [ -n "${{ github.event.workflow_run.head_sha }}" ]; then
            printf 'Analyzing changes since: %s\n' "${{ github.event.workflow_run.head_sha }}"
            python scripts/file_version_tracker.py --git-diff "${{ github.event.workflow_run.head_sha }}" \
              > "logs/aar/change-analysis-${GITHUB_RUN_ID}.md"
          fi

      - name: "Cleanup old snapshots"
        run: |
          source .venv/bin/activate
          python scripts/file_version_tracker.py --cleanup 20

      - name: "AAR summary"
        run: |
          echo "AAR Generation Summary"
          echo "====================="
          printf 'Workflow Run ID: %s\n' "${{ github.event.workflow_run.id || github.event.inputs.workflow_run_id || 'N/A' }}"
          printf 'Trigger: %s\n' "${{ github.event.workflow_run.name || 'manual' }}"
          echo "Token Policy: No Default Token Policy v1.0 COMPLIANT"
          echo "Reports Generated:"
          if [ -d "logs/aar" ]; then
            ls -la logs/aar/*.md 2>/dev/null || echo "  No AAR reports found"
          fi
          echo ""
          echo "Artifacts:"
          if [ -d "logs/token-audit" ]; then
            ls -la logs/token-audit/*.json 2>/dev/null || echo "  No token audit files found"
          fi

  security-audit:
    name: "AAR Security Audit"
    runs-on: ubuntu-24.04
    needs: generate-aar
    if: always()

    permissions:
      contents: read
      security-events: write

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Python environment"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: "Create virtual environment"
        run: |
          python -m venv .venv
          source .venv/bin/activate
          printf "VIRTUAL_ENV=%s\n" "$VIRTUAL_ENV" >> $GITHUB_ENV
          printf "%s/bin\n" "$VIRTUAL_ENV" >> $GITHUB_PATH

      - name: "Install dependencies"
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -e .[test]

      - name: "Create logs directory"
        run: |
          mkdir -p logs logs/aar logs/aar-reports logs/token-audit logs/compliance-reports

      - name: "Download AAR artifacts"
        uses: actions/download-artifact@v4
        with:
          name: "aar-reports-${{ github.run_id }}"
          path: "aar-artifacts/"
        continue-on-error: true

      # --- Token selection (policy: CI_ISSUE_AUTOMATION_TOKEN -> CI_BOT_TOKEN -> built-in) ---
      - name: "Select automation token"
        id: pick-token
        shell: bash
        env:
          S1: ${{ secrets.CI_ISSUE_AUTOMATION_TOKEN }}
          S2: ${{ secrets.CI_BOT_TOKEN }}
          BUILTIN: ${{ github.token }}
        run: |
          if [ -n "$S1" ]; then TOKEN="$S1";
          elif [ -n "$S2" ]; then TOKEN="$S2";
          else TOKEN="$BUILTIN"; fi
          printf 'token=%s\n' "$TOKEN" >> "$GITHUB_OUTPUT"
          if [ "$TOKEN" = "$BUILTIN" ]; then
            echo "::notice title=Token Selection::Using BUILT-IN token (fallback)"
          else
            echo "::notice title=Token Selection::Using FINE-GRAINED secret"
          fi

      - name: "Audit token usage compliance"
        env:
          CI_ISSUE_AUTOMATION_TOKEN: ${{ secrets.CI_ISSUE_AUTOMATION_TOKEN }}
          CI_BOT_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          GITHUB_TOKEN: ${{ steps.pick-token.outputs.token }}
        run: |
          source .venv/bin/activate
          echo "Performing AAR security audit..."
          python scripts/aar_security.py > "logs/aar-security-audit-${GITHUB_RUN_ID}.md"
          echo "Token compliance audit completed"

      - name: "Validate Potato Policy compliance"
        run: |
          source .venv/bin/activate

          # Ensure AAR system respects Enhanced Potato Policy
          bash scripts/check_potato_ignore.sh

          # Check for any sensitive data exposure in AAR reports
          if [ -d "aar-artifacts" ]; then
            grep -r "GITHUB_TOKEN\|CI_BOT_TOKEN\|CI_ISSUE_AUTOMATION_TOKEN" aar-artifacts/ || true
            echo "Sensitive token check completed"
          fi

      - name: "Archive security audit"
        uses: actions/upload-artifact@v4
        with:
          name: "aar-security-audit-${{ github.run_id }}"
          path: |
            logs/aar-security-*.md
          retention-days: 30
