#
# WORKFLOW: audit-workflow-headers
# PURPOSE: Ensures all workflows have proper token and policy documentation
# TOKEN: GITHUB_TOKEN (read-only validation)
# PERMISSIONS: Minimal read permissions for file access
#
# MAINTENANCE NOTES:
# - Triggers when workflow files are modified
# - Validates header compliance across all workflows
# - Ensures token usage and policy compliance is documented
#
# COMPLIANCE:
# CodeQL security requirements satisfied
# Token policy hierarchy respected
# Branch protection integration verified
# Production hardening applied
#
name: Audit Workflow Headers

on:
  pull_request:
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Audit workflow headers for compliance
        run: |
          chmod +x scripts/audit-workflow-headers.sh
          ./scripts/audit-workflow-headers.sh
