name: Extract Bot SSH Public Key (DEPRECATED - Use GPG Signing)
# DEPRECATED: This workflow is no longer needed as DevOnboarder has migrated to unified GPG signing.
# See: scripts/setup_bot_gpg_key.sh for the new GPG-based automation setup.
# Priority Matrix Bot now uses GPG signing instead of SSH for consistent signature verification.

on:
  workflow_dispatch:

jobs:
  extract-key:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Extract SSH public key
        env:
          PMBOT_SSH_PRIVATE: ${{ secrets.PMBOT_SSH_PRIVATE }}
        run: |
          umask 077
          mkdir -p ~/.ssh

          # Decode and save private key
          printf '%s' "$PMBOT_SSH_PRIVATE" | base64 -d > ~/.ssh/ci_signing_key
          chmod 600 ~/.ssh/ci_signing_key

          # Generate public key
          ssh-keygen -y -f ~/.ssh/ci_signing_key > ~/.ssh/ci_signing_key.pub

          echo "WARNING: DEPRECATED - SSH signing has been replaced with GPG signing"
          echo "=============================================="
          echo "Bot SSH Public Key (LEGACY - NO LONGER USED):"
          cat ~/.ssh/ci_signing_key.pub
          echo "=============================================="
          echo ""
          echo "MIGRATION: Use GPG signing instead:"
          echo "1. Run: bash scripts/setup_bot_gpg_key.sh"
          echo "2. GPG keys are now managed via GitHub secrets"
          echo "3. Priority Matrix Bot uses unified GPG signing"
          echo "4. See GitHub issue #1575 for migration details"
