name: Extract Bot SSH Public Key

on:
  workflow_dispatch:

jobs:
  extract-key:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Extract SSH public key
        env:
          PMBOT_SSH_PRIVATE: ${{ secrets.PMBOT_SSH_PRIVATE }}
        run: |
          umask 077
          mkdir -p ~/.ssh

          # Decode and save private key
          printf '%s' "$PMBOT_SSH_PRIVATE" | base64 -d > ~/.ssh/ci_signing_key
          chmod 600 ~/.ssh/ci_signing_key

          # Generate public key
          ssh-keygen -y -f ~/.ssh/ci_signing_key > ~/.ssh/ci_signing_key.pub

          echo "Bot SSH Public Key (copy this to GitHub):"
          echo "=============================================="
          cat ~/.ssh/ci_signing_key.pub
          echo "=============================================="
          echo ""
          echo "Steps to fix verification:"
          echo "1. Copy the public key above"
          echo "2. Go to: https://github.com/settings/keys"
          echo "3. Click 'New SSH key'"
          echo "4. Title: 'Priority Matrix Bot Signing Key'"
          echo "5. Key type: 'Signing Key'"
          echo "6. Paste the public key"
          echo "7. Click 'Add SSH key'"
